name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: apt update && \
           apt install -y lsb-release gnupg wget sudo && \
           export DEBIAN_FRONTEND="noninteractive" && \
           wget https://repo.mysql.com/mysql-apt-config_0.8.22-1_all.deb && \
           dpkg -i -E mysql-apt-config_0.8.22-1_all.deb && \
           apt update && \
           apt upgrade -y && \
           apt install -y libtbb2 libmysqlcppconn-dev mysql-shell mysql-client && \
           sudo cp /usr/lib/x86_64-linux-gnu/*.so /lib
    - name: Build
      run: mkdir -p build && cd build && cmake .. && make . && cmake --build .
